import { ChangeEvent, FunctionComponent, JSX, useMemo, useState } from 'react';
import CloudUploadOutlinedIcon from '@mui/icons-material/CloudUploadOutlined';
import DownloadOutlinedIcon from '@mui/icons-material/DownloadOutlined';
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined';
import {
  Alert,
  Box,
  Button,
  CircularProgress,
  List,
  ListItem,
  ListItemText,
  DialogActions,
  DialogContent,
  DialogTitle,
  Typography,
} from '@mui/material';
import * as XLSX from 'xlsx';

import { isAxiosError } from 'axios';

import { HandleUploadPatientXlsx } from '../api/handlers';
import { PatientStateProps, PatientUploadResultModel } from '../api/types';

const ACCEPTED_EXTENSIONS = ['.xlsx', '.csv'];
const TEMPLATE_HEADERS = [
  'FirstName',
  'LastName',
  'MiddleName',
  'EmailAddress',
  'BirthDate',
  'ContactNumber',
  'Address',
  'Suffix',
  'Occupation',
  'Religion',
  'BloodType',
  'CivilStatus',
];
const TEMPLATE_SAMPLE_ROW = TEMPLATE_HEADERS.map(() => '');
const REFERENCE_ROWS = [
  ['Field', 'Allowed Values / Notes'],
  ['FirstName', 'Required text'],
  ['LastName', 'Required text'],
  ['MiddleName', 'Optional text'],
  ['EmailAddress', 'Optional email address'],
  ['BirthDate', 'Use YYYY-MM-DD format'],
  ['ContactNumber', 'Optional text'],
  ['Address', 'Optional text'],
  ['Suffix', 'None'],
  [
    'BloodType',
    'A_Positive, A_Negative, B_Positive, B_Negative, AB_Positive, AB_Negative, O_Positive, O_Negative',
  ],
  ['CivilStatus', 'None, Single, Married, Divorced, Widowed'],
  ['Occupation', 'Optional text'],
  ['Religion', 'Optional text'],
  ['PatientNumber', 'Auto-generated by backend. Do not include in upload file.'],
  ['Tag', 'Not included in this template.'],
];

type PatientUploadModalProps = PatientStateProps & {
  clinicId?: string | null;
};

const PatientUploadModal: FunctionComponent<PatientUploadModalProps> = (
  props: PatientUploadModalProps
): JSX.Element => {
  const { state, setState, clinicId } = props;
  const [selectedFile, setSelectedFile] = useState<File | undefined>();
  const [errorMessage, setErrorMessage] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [uploadResult, setUploadResult] = useState<PatientUploadResultModel | undefined>();

  const fileLabel = useMemo(() => selectedFile?.name || 'No file selected.', [selectedFile]);

  const handleClose = (): void => {
    setSelectedFile(undefined);
    setErrorMessage('');
    setUploadResult(undefined);
    setState({
      ...state,
      openModal: false,
      upload: false,
    });
  };

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>): void => {
    const file = event.target.files?.[0];

    if (!file) {
      setSelectedFile(undefined);
      setErrorMessage('');
      return;
    }

    const normalizedName = file.name.toLowerCase();
    const isValidFile = ACCEPTED_EXTENSIONS.some((extension) => normalizedName.endsWith(extension));

    if (!isValidFile) {
      setSelectedFile(undefined);
      setErrorMessage('Only .xlsx and .csv files are allowed.');
      return;
    }

    setSelectedFile(file);
    setErrorMessage('');
    setUploadResult(undefined);
  };

  const handleDownloadTemplate = (): void => {
    const worksheet = XLSX.utils.aoa_to_sheet([TEMPLATE_HEADERS, TEMPLATE_SAMPLE_ROW]);
    const referenceSheet = XLSX.utils.aoa_to_sheet(REFERENCE_ROWS);
    const workbook = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(workbook, worksheet, 'Patients');
    XLSX.utils.book_append_sheet(workbook, referenceSheet, 'Reference');
    XLSX.writeFile(workbook, 'patient-import-template.xlsx');
  };

  const handleUpload = async (): Promise<void> => {
    if (!selectedFile) {
      return;
    }

    setErrorMessage('');
    setIsSubmitting(true);

    try {
      const response = await HandleUploadPatientXlsx(selectedFile, state, setState, clinicId);
      setUploadResult(response);
      setSelectedFile(undefined);
    } catch (error) {
      if (isAxiosError(error)) {
        setErrorMessage(
          typeof error.response?.data === 'string' ? error.response.data : error.message
        );
      } else {
        setErrorMessage('Unable to upload patient file.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      <DialogTitle sx={{ pb: 1, fontWeight: 700 }}>Upload Patient File</DialogTitle>
      <DialogContent dividers sx={{ px: { xs: 2, sm: 3 }, py: 2 }}>
        {errorMessage ? (
          <Alert severity="error" sx={{ mb: 2 }}>
            {errorMessage}
          </Alert>
        ) : null}
        {uploadResult ? (
          <Alert severity={uploadResult.skippedCount > 0 ? 'warning' : 'success'} sx={{ mb: 2 }}>
            Imported: {uploadResult.importedCount} | Skipped: {uploadResult.skippedCount} | Rows:{' '}
            {uploadResult.totalRows}
          </Alert>
        ) : null}
        {isSubmitting ? (
          <Alert
            severity="info"
            icon={<CircularProgress size={18} color="inherit" />}
            sx={{ mb: 2 }}
          >
            Uploading patient file. Please wait...
          </Alert>
        ) : null}

        <Box
          sx={{
            border: '1px dashed rgba(22, 119, 168, 0.35)',
            borderRadius: 2,
            backgroundColor: 'rgba(22, 119, 168, 0.03)',
            p: 3,
            display: 'flex',
            flexDirection: 'column',
            gap: 2,
            alignItems: 'center',
            textAlign: 'center',
          }}
        >
          <Box
            sx={{
              width: 64,
              height: 64,
              borderRadius: '18px',
              backgroundColor: '#e9f4fb',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#1e6f9f',
            }}
          >
            <DescriptionOutlinedIcon sx={{ fontSize: 34 }} />
          </Box>

          <Box>
            <Typography sx={{ fontWeight: 700, color: '#284764', mb: 0.5 }}>
              Select an import file
            </Typography>
            <Typography variant="body2" sx={{ color: 'text.secondary' }}>
              Upload patient records from an `.xlsx` or `.csv` file. The import uses the same
              `PatientInfo` backend field names in both formats.
            </Typography>
          </Box>

          <Box
            sx={{
              display: 'flex',
              flexDirection: { xs: 'column', sm: 'row' },
              gap: 1.5,
              width: '100%',
              justifyContent: 'center',
            }}
          >
            <Button
              variant="outlined"
              startIcon={<DownloadOutlinedIcon />}
              onClick={handleDownloadTemplate}
              disabled={isSubmitting}
            >
              Download Template
            </Button>
            <Button
              component="label"
              variant="outlined"
              startIcon={<CloudUploadOutlinedIcon />}
              disabled={isSubmitting}
            >
              Choose XLSX/CSV File
              <input hidden type="file" accept=".xlsx,.csv,text/csv" onChange={handleFileChange} />
            </Button>
          </Box>

          <Typography variant="body2" sx={{ color: '#415c74' }}>
            {fileLabel}
          </Typography>
        </Box>

        {uploadResult?.errors?.length ? (
          <Box
            sx={{
              mt: 2,
              border: '1px solid rgba(217, 119, 6, 0.28)',
              borderRadius: 2,
              backgroundColor: '#fffaf2',
              maxHeight: 180,
              overflowY: 'auto',
            }}
          >
            <Typography
              sx={{
                px: 2,
                pt: 1.5,
                fontWeight: 700,
                color: '#9a5b00',
              }}
            >
              Upload Errors
            </Typography>
            <List dense sx={{ pt: 0.5, pb: 1 }}>
              {uploadResult.errors.map((error, index) => (
                <ListItem key={`${error}-${index}`} sx={{ py: 0.25 }}>
                  <ListItemText
                    primary={error}
                    primaryTypographyProps={{
                      fontSize: 13,
                      color: '#7c4a03',
                    }}
                  />
                </ListItem>
              ))}
            </List>
          </Box>
        ) : null}
      </DialogContent>
      <DialogActions sx={{ px: 3, py: 2 }}>
        <Button onClick={handleClose} color="inherit">
          Cancel
        </Button>
        <Button variant="contained" disabled={!selectedFile || isSubmitting} onClick={handleUpload}>
          {isSubmitting ? 'Uploading...' : 'Upload'}
        </Button>
      </DialogActions>
    </>
  );
};

export default PatientUploadModal;
