import * as XLSX from 'xlsx';

const PATIENT_TEMPLATE_HEADERS = [
  'FirstName',
  'LastName',
  'MiddleName',
  'EmailAddress',
  'BirthDate',
  'ContactNumber',
  'Address',
  'Suffix',
  'Occupation',
  'Religion',
  'BloodType',
  'CivilStatus',
  'Gender',
];

const PATIENT_REFERENCE_ROWS = [
  ['Field', 'Allowed Values / Notes'],
  ['FirstName', 'Required text'],
  ['LastName', 'Required text'],
  ['MiddleName', 'Optional text'],
  ['EmailAddress', 'Optional email address'],
  ['BirthDate', 'Use YYYY-MM-DD format'],
  ['ContactNumber', 'Optional text'],
  ['Address', 'Optional text'],
  ['Suffix', 'None'],
  [
    'BloodType',
    'A_Positive, A_Negative, B_Positive, B_Negative, AB_Positive, AB_Negative, O_Positive, O_Negative',
  ],
  ['CivilStatus', 'None, Single, Married, Divorced, Widowed'],
  ['Gender', 'Male, Female, Others'],
  ['Occupation', 'Optional text'],
  ['Religion', 'Optional text'],
  ['PatientNumber', 'Auto-generated by backend. Do not include in upload file.'],
  ['Tag', 'Not included in this template.'],
];

export const downloadPatientImportTemplate = (): void => {
  const worksheet = XLSX.utils.aoa_to_sheet([
    PATIENT_TEMPLATE_HEADERS,
    PATIENT_TEMPLATE_HEADERS.map(() => ''),
  ]);
  const referenceSheet = XLSX.utils.aoa_to_sheet(PATIENT_REFERENCE_ROWS);
  const workbook = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(workbook, worksheet, 'Patients');
  XLSX.utils.book_append_sheet(workbook, referenceSheet, 'Reference');
  XLSX.writeFile(workbook, 'patient-import-template.xlsx');
};
